# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b72b72712aff73c02e535697ae277a873d4453ab746f9b44de27bf384dfcb384d46d5065f789208d507a98aa4556bb1621e2a89803224e5eb0f1f63f2cc146f6

test:
  secret_key_base: 11b1012310bed49a32428ae8f553f0fd9f90fe1f26623ff879112a3364411228924fddb1bb0e66049266bfff91abe767db14f94b35c6dd1a92165bb000e19957

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
